# Algorithm
DEFAULT_LINKAGE_MODEL = "UNIVARIATE"
DEFAULT_POPULATION_SIZE = 32
DEFAULT_NUM_POPULATIONS = 1
DEFAULT_TAU = 0.35
DEFAULT_DISTRIBUTION_MULTIPLIER_DECREASE = 0.9
DEFAULT_ST_DEV_THRESHOLD = 1.0
DEFAULT_RANDOM_SEED = -1

# Problem
DEFAULT_PROBLEM = "SPHERE"
DEFAULT_DIMENSIONALITY = 2
DEFAULT_BLACK_BOX = False
DEFAULT_LOWER_INIT_BOUND = -10
DEFAULT_UPPER_INIT_BOUND = 10
DEFAULT_VTR = 1e-10
DEFAULT_ROTATION_ANGLE = 0.0

# Computation Budget
DEFAULT_MAX_NUM_EVALUATIONS = 1e7
DEFAULT_MAX_NUM_SECONDS = 3 * 60.0 * 60.0
DEFAULT_MAX_NO_IMPROVEMENT_STRETCH = 100
DEFAULT_FITNESS_VARIANCE_TOLERANCE = 1e-20

# Experiments
DEFAULT_NUM_BISECTION_REPEATS = 5
DEFAULT_NUM_REPEATS_PER_BISECTION_TEST = 30
